### ISSUE TITLE
Do "pointClick" events work with Ember?

### ISSUE THREAD

**Issue by wonderful123** [AnyChart/AnyChart-Ember#1]
How do you use click listeners for a stock chart? I want to get the date for a click and create a drilldown chart.

**Comment by Shestac92** [comment]
@wonderful123 It's possible with a listener and some extra code. [Here is a sample](https://jsfiddle.net/tq28vkh3/) of implementing this feature. You can use the same approach in Ember project. Please, download our [AnyChart-Ember demo](https://github.com/AnyChart/AnyChart-Ember). Then replace AnyChart-Ember/tests/dummy/app/routes/simple-stock-chart.js file with [modified file](https://gist.githubusercontent.com/Shestac92/6065e4be1aace7c6c11574e949af4be8/raw/f3efc95940d7d6599206fa9a862aebd1f5cbb0b7/simple-stock-chart.js).
Then you can launch demo and choose 'simple-stock-chart' and try to click on the plot. You will see date and data from the clicked point in the chart title and in the browser console.

**Comment by wonderful123** [comment]
Very cool. I don't think I would have come up with all that easily!

**Comment by wonderful123** [comment]
This code is actually buggy. The returned date is depending on which side of the selection line is clicked.

https://www.screencast.com/t/hkkwrnHn7x1V

You can't see the cursor with the screenshot software but I'm clicking either side of the selection line.

**Comment by Shestac92** [comment]
@wonderful123 
This may come from different dateTime formats (UTC and using timeZone). Do you set your data as UTC dateTime? Do you define any dateTime formats in your project?
Javascript methodes use timeZone offset, sometimes it brings troubles.

**Comment by wonderful123** [comment]
Oh I think you're right. I'm at 12pm for each time. Thanks very much!
